### ISSUE TITLE
Invalid argument with USB Keyboard input

### ISSUE THREAD

**Issue by cjcdev** [athombv/node-linux-input-device#1]
I get the following error when I run the example on Mint 17.3 with a USB keyboard.  

Error: Invalid argument                                                                                                                                                      
    at Error (native)

**Comment by jeroenvollenbrock** [comment]
Could you try running the example without the last line of code?

**Comment by cjcdev** [comment]
It seems to be the same result.  The error happens the first time it gets an input event.  Since I'm watching keyboard input it returns the error immediately after running "node index.js" because it's reading the [enter key] input.  If I delay it with a sleep "sleep 1 && node index.js", the code will wait until the first key press and then throw the error again.

Are you able to get this running on your machine?

**Comment by jeroenvollenbrock** [comment]
I've released version 2.0.0 a few weeks ago which might fix the issue. Could you let me know if that works? Sadly i'm not able to actively provide more support on this project.
